### ISSUE TITLE
dockerfile 哪位大佬额能提供一个，想要稳定运行, 就必须容器化部署才能高可用...

### ISSUE THREAD

**Issue by gowy222** [beikeshop/beikeshop#52]
构建基础环境用什么版本的基座? 
主要同样php81,  
Installing php81-fileinfo (8.1.28-r0) 
但是  "ext-fileinfo": "*",

各种报错
  Problem 4
#10 9.419     - intervention/image is locked to version 2.7.2 and an update of this package was not requested.
#10 9.419     - intervention/image 2.7.2 requires ext-fileinfo * -> it is missing from your system. Install or enable PHP's fileinfo extension.

**Comment by GuangdaNetwork** [comment]
https://github.com/beikeshop/BeikeShop-docker

**Comment by easonjim** [comment]
@GuangdaNetwork https://github.com/beikeshop/BeikeShop-docker
这个地址无效了
