### ISSUE TITLE
邮件配置失败

### ISSUE THREAD

**Issue by Yeyunrong** [beikeshop/beikeshop#59]
在网站后台配置邮件信息，但是邮件发不出去，看日志报错为：.ERROR: Expected response code "250" but got code "501"。
![t1](https://github.com/beikeshop/beikeshop/assets/26713099/4205f0f6-c225-4ae0-9743-d05eab57f956)

参考官网文档的 【系统设置-基础设置的邮箱是否和邮件设置里的用户一致】修改和这是， 判断为一致。

**Comment by pushuo** [comment]
请确定与 系统设置 -> 基础设置的邮箱是否一致 [这一点很重要]，如果是一致的话 检查一下邮箱设置，是否开启 SMTP 服务。 
或者在官网提工单给我们

**Comment by chinaheao** [comment]
为什么要基础设置里的邮箱和邮件设置的邮箱一样呢，这样设置是不是有点反人性
