### ISSUE TITLE
部署安装时出现错误

### ISSUE THREAD

**Issue by wangliyang206** [beikeshop/beikeshop#61]
Warning: require(/www/wwwroot/beikeshop/public/../vendor/autoload.php): Failed to open stream: No such file or directory in /www/wwwroot/beikeshop/public/index.php on line 58

Fatal error: Uncaught Error: Failed opening required '/www/wwwroot/beikeshop/public/../vendor/autoload.php' (include_path='.:') in /www/wwwroot/beikeshop/public/index.php:58 Stack trace: #0 {main} thrown in /www/wwwroot/beikeshop/public/index.php on line 58

未找到 vendor/autoload.php 这个文件，请问怎么解决？

**Comment by pushuo** [comment]
没有执行 composer install?
