### ISSUE TITLE
How to get multi vendor plugin

### ISSUE THREAD

**Issue by oulfr** [beikeshop/beikeshop#70]
Hello,
How to get multi vendor plugin ?

Regrads,

**Comment by oulfr** [comment]
any news ?

**Comment by pushuo** [comment]
Hello.
please check [https://beikeshop.com/solution/b2b2c](url)

**Comment by GuangdaNetwork** [comment]
You need to purchase it to get it, please contact sales@guangda.work by email @oulfr

**Comment by GuangdaNetwork** [comment]
the end
